#!/bin/bash
#
# EmP Check-In — Full Setup Script
#
# Reads secrets from ~/.emp-checkin/config.env (or prompts if missing).
# Preprocesses rosters, generates embedded data, app icons, and Xcode project.
#
# Usage:
#   ./scripts/setup.sh
#

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "═══════════════════════════════════════════"
echo "  EmP Check-In — Setup"
echo "═══════════════════════════════════════════"
echo ""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

CONFIG_DIR="$HOME/.emp-checkin"
CONFIG_FILE="$CONFIG_DIR/config.env"

# Step 1: Load or prompt for secrets
echo -e "${YELLOW}[1/9]${NC} Loading secrets..."

if [ -f "$CONFIG_FILE" ]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    echo "  ✓ Loaded $CONFIG_FILE"
else
    echo -e "${YELLOW}  Config not found at $CONFIG_FILE${NC}"
    echo "  Let's create it now."
    mkdir -p "$CONFIG_DIR"
    chmod 700 "$CONFIG_DIR"

    read -r -p "  QIAN password (EmP Qiān, volunteers): " QIAN_PASSWORD
    read -r -p "  DAO password (EmP Dào, athletes): " DAO_PASSWORD
    read -r -p "  TONG password (EmP Tōng, admin): " TONG_PASSWORD
    read -r -p "  EXPORT PIN (4 digits for AirDrop): " EXPORT_PIN

    {
        echo "# EmP Check-In — secrets and configuration"
        echo ""
        echo "DAO_PASSWORD=$DAO_PASSWORD"
        echo "QIAN_PASSWORD=$QIAN_PASSWORD"
        echo "TONG_PASSWORD=$TONG_PASSWORD"
        echo "EXPORT_PIN=$EXPORT_PIN"
    } > "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
    echo "  ✓ Saved to $CONFIG_FILE"
fi

# Validate
for var in DAO_PASSWORD QIAN_PASSWORD TONG_PASSWORD EXPORT_PIN; do
    if [ -z "${!var}" ]; then
        echo -e "${RED}Error:${NC} $var is empty. Edit $CONFIG_FILE."
        exit 1
    fi
done

# Step 2: Check prerequisites
echo ""
echo -e "${YELLOW}[2/9]${NC} Checking prerequisites..."

if ! command -v uv &> /dev/null; then
    echo -e "${RED}Error:${NC} 'uv' not found."
    exit 1
fi
echo "  ✓ uv"

if ! command -v xcodegen &> /dev/null; then
    echo -e "${YELLOW}  Installing xcodegen...${NC}"
    brew install xcodegen
fi
echo "  ✓ xcodegen"

# Step 3: Ensure roster xlsx files exist in data/
echo ""
echo -e "${YELLOW}[3/9]${NC} Checking roster files..."

mkdir -p data

prompt_for_xlsx() {
    local target="$1"
    local label="$2"

    if [ -f "$target" ]; then
        echo "  ✓ $target"
        return
    fi

    echo -e "  ${YELLOW}⚠️  $target not found${NC}"
    echo ""
    echo "  Provide the absolute path to $label.xlsx"
    echo "  (tip: use 'realpath <file>' to get the full path)"

    while true; do
        read -r -p "  > " src_path
        if [ -z "$src_path" ]; then
            echo -e "  ${RED}Path cannot be empty.${NC}"
            continue
        fi
        # Expand ~ if present
        src_path="${src_path/#\~/$HOME}"
        if [ ! -f "$src_path" ]; then
            echo -e "  ${RED}File not found: $src_path${NC}"
            continue
        fi
        cp "$src_path" "$target"
        echo "  ✓ Copied to $target"
        break
    done
}

prompt_for_xlsx "data/athletes.xlsx" "athletes"
prompt_for_xlsx "data/volunteers.xlsx" "volunteers"

# Step 3: Clean previous artifacts
echo ""
echo -e "${YELLOW}[4/9]${NC} Cleaning previous artifacts..."
rm -rf app_bundle
rm -rf EmPCheckIn/EmPCheckIn.xcodeproj
rm -rf EmPCheckIn/Sources/*/Assets.xcassets
rm -f EmPCheckIn/Sources/Shared/Services/EmbeddedData.swift
rm -f EmPCheckIn/Sources/Shared/Services/Secrets.swift
rm -rf ~/Library/Developer/Xcode/DerivedData/EmPCheckIn-*
echo "  ✓ Clean"

# Step 4: Install Python dependencies
echo ""
echo -e "${YELLOW}[5/9]${NC} Installing Python dependencies..."
uv sync --quiet
echo "  ✓ Dependencies installed"

# Step 5: Preprocess rosters
echo ""
echo -e "${YELLOW}[6/9]${NC} Preprocessing rosters..."
uv run python scripts/prepare_roster.py \
    --password-dao "$DAO_PASSWORD" \
    --password-qian "$QIAN_PASSWORD" \
    --password-tong "$TONG_PASSWORD"

# Step 6: Generate Secrets.swift and EmbeddedData.swift
echo ""
echo -e "${YELLOW}[7/9]${NC} Generating Swift files (Secrets, EmbeddedData)..."

cat > EmPCheckIn/Sources/Shared/Services/Secrets.swift << SWIFTEOF
import Foundation

// Auto-generated by scripts/setup.sh — DO NOT COMMIT.
enum Secrets {
    static let exportPIN = "$EXPORT_PIN"
}
SWIFTEOF
echo "  ✓ Secrets.swift written"

uv run python -c "
import base64
import json
from pathlib import Path

dao = base64.b64encode(Path('app_bundle/athletes_dao.enc').read_bytes()).decode()
qian = base64.b64encode(Path('app_bundle/volunteers_qian.enc').read_bytes()).decode()
tong_a = base64.b64encode(Path('app_bundle/athletes_tong.enc').read_bytes()).decode()
tong_v = base64.b64encode(Path('app_bundle/volunteers_tong.enc').read_bytes()).decode()

# Load available ages (unencrypted metadata)
ages_dao = json.loads(Path('app_bundle/ages_dao.json').read_text())
ages_swift = ', '.join(str(a) for a in ages_dao)

swift = '''import Foundation

// Auto-generated by scripts/setup.sh — DO NOT COMMIT.
enum EmbeddedData {
    static let athletesDaoBase64 = \"\"\"
''' + dao + '''
\"\"\"

    static let volunteersQianBase64 = \"\"\"
''' + qian + '''
\"\"\"

    static let athletesTongBase64 = \"\"\"
''' + tong_a + '''
\"\"\"

    static let volunteersTongBase64 = \"\"\"
''' + tong_v + '''
\"\"\"

    // Available ages for EmP Dao (athlete check-in) - from roster data
    static let availableAgesDao: [Int] = [''' + ages_swift + ''']

    static var athletesDaoData: Data { Data(base64Encoded: athletesDaoBase64)! }
    static var volunteersQianData: Data { Data(base64Encoded: volunteersQianBase64)! }
    static var athletesTongData: Data { Data(base64Encoded: athletesTongBase64)! }
    static var volunteersTongData: Data { Data(base64Encoded: volunteersTongBase64)! }
}
'''

Path('EmPCheckIn/Sources/Shared/Services/EmbeddedData.swift').write_text(swift)
print('  ✓ EmbeddedData.swift written')
"

# Step 7: Generate app icons
echo ""
echo -e "${YELLOW}[8/9]${NC} Generating app icons..."
uv run python -c "
from PIL import Image, ImageDraw, ImageFont
import os, json

def make_icon(text, bg_color, size, output_path):
    img = Image.new('RGB', (size, size), bg_color)
    draw = ImageDraw.Draw(img)
    font_size = int(size * 0.35)
    font = ImageFont.truetype('/System/Library/Fonts/STHeiti Medium.ttc', font_size, index=0)
    bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    x = (size - tw) / 2 - bbox[0]
    y = (size - th) / 2 - bbox[1]
    draw.text((x, y), text, fill='white', font=font)
    img.save(output_path)

apps = [
    ('Qiān', (124, 58, 237), 'Qian'),
    ('Dào', (16, 185, 129), 'Dao'),
    ('Tōng', (71, 85, 105), 'Tong'),
]

for text, color, name in apps:
    icon_dir = f'EmPCheckIn/Sources/{name}/Assets.xcassets/AppIcon.appiconset'
    os.makedirs(icon_dir, exist_ok=True)
    make_icon(text, color, 1024, f'{icon_dir}/icon_1024.png')
    contents = {'images': [{'filename': 'icon_1024.png', 'idiom': 'universal', 'platform': 'ios', 'size': '1024x1024'}], 'info': {'author': 'xcode', 'version': 1}}
    with open(f'{icon_dir}/Contents.json', 'w') as f:
        json.dump(contents, f)
    root_json = f'EmPCheckIn/Sources/{name}/Assets.xcassets/Contents.json'
    with open(root_json, 'w') as f:
        json.dump({'info': {'author': 'xcode', 'version': 1}}, f)

print('  ✓ Icons generated: Dào, Qiān, Tōng')
"

# Step 8: Generate Xcode project
echo ""
echo -e "${YELLOW}[9/9]${NC} Generating Xcode project..."
cd EmPCheckIn
xcodegen generate --spec project.yml
cd ..

# Verify
echo ""
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Setup complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo ""

MISSING=""
for app in Dao Qian Tong; do
    if [ ! -f "EmPCheckIn/Sources/$app/Assets.xcassets/AppIcon.appiconset/icon_1024.png" ]; then
        MISSING="$MISSING $app"
    fi
done
if [ -n "$MISSING" ]; then
    echo -e "  ${RED}⚠️  Missing icons for:$MISSING${NC}"
else
    echo "  ✓ All app icons verified"
fi

[ -f "EmPCheckIn/Sources/Shared/Services/EmbeddedData.swift" ] && echo "  ✓ EmbeddedData.swift" || echo -e "  ${RED}⚠️  EmbeddedData.swift missing${NC}"
[ -f "EmPCheckIn/Sources/Shared/Services/Secrets.swift" ] && echo "  ✓ Secrets.swift" || echo -e "  ${RED}⚠️  Secrets.swift missing${NC}"
[ -d "EmPCheckIn/EmPCheckIn.xcodeproj" ] && echo "  ✓ Xcode project" || echo -e "  ${RED}⚠️  Xcode project missing${NC}"

echo ""
echo "  Config: $CONFIG_FILE"
echo ""
echo "  Next:"
echo "    ./scripts/open.sh"
echo ""
